### ISSUE TITLE
[FEATURE] - Current Project Selection Indicator 

### ISSUE THREAD

**Issue by mostafaabobakr7** [alefragnani/vscode-project-manager#524]
_Thank you for the extension great effort_

**If possible please consider** 
### Adding an indicator to the current project opened and make it un clickable maybe with

```css
.selected {
  color: --var(--custom-setting-color-with-default-green);
  cursor: default:
  pointer-events: none;
}
```

Thank you

![image](https://user-images.githubusercontent.com/27288406/123481670-59d0c700-d604-11eb-8ae5-da7118817675.png)
